src/Entity/DocumentSubCategory.php
<?php

namespace App\Entity;

use App\Repository\DocumentSubCategoryRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=DocumentSubCategoryRepository::class)
 */
class DocumentSubCategory
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\ManyToOne(targetEntity=DocumentCategory::class, inversedBy="documentSubCategories")
     * @ORM\JoinColumn(nullable=false)
     */
    private $ParentCategory;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getParentCategory(): ?DocumentCategory
    {
        return $this->ParentCategory;
    }

    public function setParentCategory(?DocumentCategory $ParentCategory): self
    {
        $this->ParentCategory = $ParentCategory;

        return $this;
    }
}

src/Form/CategoryType.php
<?php

namespace App\Form;

use App\Entity\DocumentCategory;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CategoryType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
        ;
    }
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => DocumentCategory::class,
        ]);
    }
}

src/Controller/admin/CategoryController.php
<?php

namespace App\Controller\admin;


use App\Entity\DocumentCategory;
use App\Form\CategoryType;
use App\Repository\DocumentCategoryRepository;
use App\Repository\DocumentSubCategoryRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CategoryController extends AbstractController
{
    /**
     * @Route("admin/category-manager", name="category_manager")
     * @param DocumentCategoryRepository $categoryRepository
     * @param DocumentSubCategoryRepository $subCategoryRepository
     * @return Response
     */
    public function index(DocumentCategoryRepository $categoryRepository, DocumentSubCategoryRepository $subCategoryRepository): Response
    {
        $allCategory = $categoryRepository->findAll();
        $allSubCategory = $subCategoryRepository->findAll();

        $newCategory = new DocumentCategory();
        $newCategoryForm = $this->createForm(CategoryType::class, $newCategory);

        return $this->render('category/index.html.twig', [
            'controller_name' => 'CategoryController',
            'allCategory'=> $allCategory,
            'allSubCategory'=> $allSubCategory,
            'newCategoryForm'=> $newCategoryForm->createView()
        ]);
    }

    /**
     * @Route("admin/category-manager/new", name="add_new_category")
     * @param Request $request
     * @param DocumentCategoryRepository $categoryRepository
     * @param EntityManagerInterface $entityManager
     * @return Response
     */
    public function addCategory(Request $request, DocumentCategoryRepository $categoryRepository, EntityManagerInterface $entityManager) : Response
    {

        if ($request->isXmlHttpRequest()){
            $data = $request->getContent();
            $data = json_decode($data, true);

            $allCategory = $categoryRepository->findAll();
            foreach ($allCategory as $category){
                if ($category->getName() === $data){
                    return $this->json(['code' => 200, 'message'=>'cette catégorie existe déja'], 200);
                }
            }
            $newCategory = new DocumentCategory();
            $newCategory->setName($data);
            $entityManager->persist($newCategory);
            $entityManager->flush();

        }

        return $this->json(['code' => 200, 'message'=>'Ca marche'], 200);


    }


}

templates/category/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gestion des catégories de documents{% endblock %}

{% block body %}
    <div class="bg-gradient-to-r from-yellow-200 via-red-200 to-pink-300 w-screen h-screen">
        {% include 'components/defaultTopNavBar.html.twig' %}
        <div id="DocumentCategoryCard " class="rounded p-4 ">
            <div class="grid grid-cols-2 gap-4  ">
                <div class="bg-white p-4 rounded shadow">Catégories</div>
                <div class=" bg-white p-4 rounded shadow">Sous-catégories</div>
                {% for category in allCategory %}
                    <div class="bg-white">
                        {{ category.name }}
                    </div>
                    <div class="bg-white">
                        {% for subcategory in allSubCategory %}
                            {% if subcategory.parentCategory.id == category.id %}
                            <div>{{ subcategory.name }}</div>
                            {% endif %}
                        {% endfor %}
                    </div>
                {% endfor %}
                <div class="bg-white p-4">

                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
{% endblock %}