src/Entity/Ressource.php
<?php

namespace App\Entity;

use App\Repository\RessourceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=RessourceRepository::class)
 */
class Ressource
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\ManyToOne(targetEntity=DocumentCategory::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    /**
     * @Assert\Positive
     * @ORM\Column(type="integer", nullable=false)
     */
    private $price;

    /**
     * @Assert\File(
     *     mimeTypes={"image/gif","image/jpeg","image/png","image/svg+xml"},
     *     mimeTypesMessage="formats autorisés : PNG,JPEG,GIF,SVG"
     * )
     */
    private $cover;

    /**
     * @ORM\Column(type="string")
     */
    private $cover_path;


    /**
     *  @Assert\File(
     *     mimeTypes={"application/pdf","application/x-pdf"},
     *     mimeTypesMessage="format autorisé : PDF"
     * )
     */
    private $file;

    /**
     * @ORM\Column(type="string")
     */
    private  $file_path;



    /**
     * @ORM\Column(type="datetime", nullable=false)
     */
    private $createAt;

    /**
     * @ORM\ManyToMany(targetEntity=Tag::class, inversedBy="ressources")
     */
    private $tags;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;



    /**
     * @ORM\ManyToMany(targetEntity=RessourcePack::class, mappedBy="ressources")
     */
    private $ressourcePacks;





    public function __construct()
    {
        $this->tags = new ArrayCollection();
        $this->ressourcePacks = new ArrayCollection();
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id): void
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param mixed $name
     */
    public function setName($name): void
    {
        $this->name = $name;
    }

    /**
     * @return mixed
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * @param mixed $category
     */
    public function setCategory($category): void
    {
        $this->category = $category;
    }

    /**
     * @return mixed
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * @param mixed $price
     */
    public function setPrice($price): void
    {
        $this->price = $price;
    }



    /**
     * @return mixed
     */
    public function getCover()
    {
        return $this->cover;
    }

    /**
     * @param File|null $coverFile
     */
    public function setCover(File $coverFile = null)
    {
        $this->cover = $coverFile;
    }

    /**
     * @return mixed
     */
    public function getFile()
    {
        return $this->file;
    }

    /**
     * @param mixed $file
     */
    public function setFile( File $file): void
    {
        $this->file = $file;
    }

    /**
     * @return mixed
     */
    public function getCoverPath()
    {
        return $this->cover_path;
    }

    /**
     * @param mixed $cover_path
     */
    public function setCoverPath($cover_path): void
    {
        $this->cover_path = $cover_path;
    }

    /**
     * @return mixed
     */
    public function getFilePath()
    {
        return $this->file_path;
    }

    /**
     * @param mixed $file_path
     */
    public function setFilePath($file_path): void
    {
        $this->file_path = $file_path;
    }




    /**
     * @return mixed
     */
    public function getCreateAt()
    {
        return $this->createAt;
    }

    /**
     * @param mixed $createAt
     */
    public function setCreateAt($createAt): void
    {
        $this->createAt = $createAt;
    }

    /**
     * @return Collection|Tag[]
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        $this->tags->removeElement($tag);

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }



    /**
     * @return Collection|RessourcePack[]
     */
    public function getRessourcePacks(): Collection
    {
        return $this->ressourcePacks;
    }

    public function addRessourcePack(RessourcePack $ressourcePack): self
    {
        if (!$this->ressourcePacks->contains($ressourcePack)) {
            $this->ressourcePacks[] = $ressourcePack;
            $ressourcePack->addRessource($this);
        }

        return $this;
    }

    public function removeRessourcePack(RessourcePack $ressourcePack): self
    {
        if ($this->ressourcePacks->removeElement($ressourcePack)) {
            $ressourcePack->removeRessource($this);
        }

        return $this;
    }







}

src/Controller/client/ClientController.php
<?php

namespace App\Controller\client;


use App\Repository\DocumentCategoryRepository;
use App\Repository\RessourceRepository;
use App\Repository\TagRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


class ClientController extends AbstractController
{

    /**
     * @Route("/client/shop", name="client_shop")
     * @param RessourceRepository $ressourceRepository
     * @param TagRepository $tagRepository
     * @param DocumentCategoryRepository $categoryRepository
     * @return Response
     */
    public function shop(RessourceRepository $ressourceRepository, TagRepository $tagRepository, DocumentCategoryRepository $categoryRepository): Response
    {
        $user = $this->getUser();
        $allRessources = $ressourceRepository->findAll();
        $tags = $tagRepository->findAll();
        $allCategory = $categoryRepository->findAll();
        $userRessources = $user->getLibrary();

        return $this->render('client/shop.html.twig', [
            'controller_name' => 'ClientController',
            'allRessources' => $allRessources,
            'allCategory' => $allCategory,
            'userRessources' => $userRessources,
            'tags' => $tags
        ]);
    }

    /**
     * @Route("/client/shop/buy/{id}", name="buy_this_items")
     * @param $id
     * @param RessourceRepository $ressourceRepository
     * @param EntityManagerInterface $entityManager
     */
    public function buyOneItems($id, RessourceRepository $ressourceRepository,  EntityManagerInterface $entityManager)
    {
        $user = $this->getUser();

        $itemToBuy = $ressourceRepository->find($id);

        foreach ($user->getLibrary() as $library)   {
            if ($library ==  $itemToBuy){
                $this->addFlash('warning','Cet item est déja dans votre bibliothèque');
                return $this->redirectToRoute('client_shop');
            }
        }

        if ($itemToBuy) {
            if ($itemToBuy->getPrice() <= $user->getCoins()) {
                $user->setCoins($user->getCoins() - $itemToBuy->getPrice());
                $user->addLibrary($itemToBuy);
                $entityManager->flush();
            }else{
                $this->addFlash('warning','Crédits insuffisants');
                return $this->redirectToRoute('client_shop');
            }
            $this->addFlash('success','Achat effectué');
        }
        return $this->redirectToRoute('client_chest');
    }

    /**
     * @Route("/client/my-chest", name="client_chest")
     * @param DocumentCategoryRepository $categoryRepository
     * @return Response
     */
    public function myChest(DocumentCategoryRepository $categoryRepository): Response
    {
        $user = $this->getUser();

        $userRessources = $user->getLibrary();
        $allCategory = $categoryRepository->findAll();

        return $this->render('client/my-chest.html.twig', [
            'controller_name' => 'ClientController',
            'userRessources' => $userRessources,
            'allCategory' => $allCategory,
        ]);
    }
}

templates/client/my-chest.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Ma bibliothèque
{% endblock %}

{% block body %}
<div class="bg-white min-h-screen w-screen flex flex-col ">
    {% include 'components/chestNavBar.html.twig' %}
    {% include 'components/shop/shopFilterBar.html.twig' %}
    <div class="flex flex-col flex-wrap px-4 pt-4">
        {% for category in allCategory %}
            <div>
                {% set countRessource = 0 %}
                {% for ressource in userRessources %}
                    {% if ressource.category.name == category.name %}
                        {% set countRessource =+1 %}
                    {% endif %}
                {% endfor %}


                {% if not countRessource == 0 %}
                    <div class="flex pl-4">
                        <h4 class="font-semibold text-white bg-indigo-500 rounded-lg mt-2 py-1 px-2 uppercase">
                            {{ category.name }} </h4>
                    </div>
                {% endif %}


                <div class="flex flex-wrap">
                    {% for ressource in userRessources %}

                        {% if ressource.category.name == category.name %}
                            <div class="productCard bg-white  w-full flex sm:flex-col sm:h-96 sm:w-64  rounded-lg shadow-lg m-4 hover:shadow-xl ">
                                <div class="cardImage h-64   sm:h-48 sm:w-full bg-cover bg-center rounded-t-lg"
                                     style='background-image: url("{{ asset(shop_covers_path ~ ressource.coverPath) }}")'
                                >
                                </div>
                                <div class="flex flex-col flex-grow p-4">
                                    <h4 class="font-semibold text-gray-700 ">{{ ressource.name }}</h4>
                                    <div class="sm:flex-grow ">
                                        <div class="flex flex-wrap content-center py-2 sm:pt-2">
                                            {% for tag in ressource.tags %}
                                                <button class="tagBtn text-xs bg-yellow-400 text-gray-700 p-1 mr-1 mb-1 rounded">{{ tag.name }}</button>
                                            {% endfor %}
                                        </div>
                                    </div>
                                    <div class="text-center">
                                        <a href="{{ asset(client_ressource_path ~ ressource.filePath) }}" target="_blank">
                                            <button class="py-2 w-full bg-green-300 text-gray-700 rounded-3xl shadow">Ouvrir</button>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/client/shop.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Boutique
{% endblock %}

{% block body %}

    <div class=" bg-green-200 sm:bg-white min-h-screen w-full flex flex-col ">
        <div class="hidden sm:block">
            {% include 'components/shop/shopNavBar.html.twig' %}
            {% include 'components/shop/shopFilterBar.html.twig' %}
        </div>
        <div class="sm:hidden">
            {% include 'components/mobileFloatingMenu.html.twig' %}
        </div>
        <div class="flex flex-col flex-wrap px-4 pt-4">
            <div class="hidden sm:block">
                {% include 'components/shop/shopMainContentLargeScreen.html.twig' %}
            </div>
            <div class="sm:hidden">
                {% include 'components/shop/shopMainContentSmallScreen.html.twig' %}
            </div>
        </div>

    </div>
{% endblock %}
    {% block javascripts %}
        {{ parent() }}
        <script src="{{ asset('scripts/toggleSecondaryNavCLientShop.js') }}">
        </script>
    {% endblock %}